version: '3'

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ps_db
      MYSQL_USER: ps_user
      MYSQL_PASSWORD: ps_password
    volumes:
     - ./mysql:/var/lib/mysql

  projectsend:
    image: linuxserver/projectsend:117
    depends_on:
      - mysql
    environment:
      MAX_UPLOAD: 10000
    ports:
      - 8000:80
    volumes:
      - ./config:/config
      - ./data:/data
